### ISSUE TITLE
HackerTarget API is broken

### ISSUE THREAD

**Issue by ssilatel** [EONRaider/ReconLib#5]
Hey, I think a change you did in the HackerTarget API has caused it to break.

In the commit _adef08753e7ca360caf0918c0595ea2cef455e30_ you moved the URL to Enum. When I call the API now I get the following error:

`HackerTarget.URL.value.scheme,`
`^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`AttributeError: 'tuple' object has no attribute 'scheme'`

This happens in the function `self.get_query_url` of the API. In the return of the function you are using `urlunparse`, and the first 2 parameters are `HackerTarget.URL.value.scheme` and `HackerTarget.URL.value.netloc`. Since `HackerTarget.URL.value` is a tuple, it doesn't recognise `.scheme` and `.netloc`.

### Proposed Change
You can use `HackerTarget.URL.value[0]` and `HackerTarget.URL.value[1]` instead of `.scheme` and `.netloc` respectively.

I wasn't sure if you want to do that or you want to find a better solution, so I didn't make a Pull Request.

**Comment by EONRaider** [comment]
You don't need to supply the URL as a parameter but, if you do, make sure you pass the full URL as in "https://api.hackertarget.com" (which is the predefined value)

**Comment by ssilatel** [comment]
I am not supplying any parameters to it. This is all being done in your repo.

**Comment by EONRaider** [comment]
I've just reviewed the code and I'm still failing to reproduce the issue you mention. The following code works perfectly and returns all known subdomains for github.com:
```
from reconlib import hackertarget

domain_info = hackertarget.API("github.com")
domain_info.hostsearch()

print(domain_info.subdomains)  # Displays 241 known hosts at this time
```

You can also run the tests for the API and see that they all pass.

**Comment by EONRaider** [comment]
Access by field name of the namedtuple that created the problem was replaced with access by index. The issue was generated by an implementation bug in CPython as described in the following conversation: https://github.com/python/cpython/issues/100098
